# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMCRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMCRxSwift
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'MVVMCRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMCRxSwiftUITests' do
    # Pods for testing
  end

end
